### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by wei-0321** [xiaobanni/Anime_Face_Generation#1]
This project was fantastic and impressive, such a great job!

May I ask you some questions?  I'm new to GAN.
1. How many steps in your dataset preparation?
2. Could you release your source code?  I want to learn how to train StyleGAN and hyperparameters setting.

Thanks!

**Comment by xiaobanni** [comment]
Thank you for your approval.
For question 1, I collected the training set according to the steps in the paper "[Towards the Automatic Anime Characters Creation with Generative Adversarial Networks](https://arxiv.org/abs/1708.05509)". 
For question 2, I used the code provided by [StyleGAN](https://github.com/NVlabs/stylegan2) directly, but I wrote the visualization window myself.
Hope my answer is helpful.

**Comment by wei-0321** [comment]
Thanks for replying!
By the way, could I ask some little questions with email?

**Comment by xiaobanni** [comment]
Okay, but I recommend communicating directly on Github.
